version: '3.1'

services:
  db:
    build: .docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database_development
      MYSQL_PASSWORD: root
      MYSQL_NATIVE_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      DB_HOSTNAME: mysql
      MYSQL_TCP_PORT: 3308
    ports:
      - 33006:3308

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: api-cadastro-medicos
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
