version: '3.1'

services:
  app:
    build: .
    command: npm run start
    ports:
      - '3000:3000'
    volumes:
      - .:/src/main

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_NATIVE_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      DB_HOSTNAME: mysql
